### ISSUE TITLE
Recently Boarded Vessels page shows incorrect crew member count

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#164]
When I do a search for recently boarded vessels (either from 'Find Records' or Board Vessel) vessels show an incorrect crew member count. See attached screenshot - Orca and Magic had only 1 boarding with 0 crew members but are showing up as having '1 crew members'. Also please change it so when there is 1 crew member it says 'member' not 'members'. This will need a new variable in localization as well.

**Comment by Sheeri** [comment]
![Screenshot_1595957032](https://user-images.githubusercontent.com/1767528/88709670-7e19e000-d0e3-11ea-847a-d942e09d90dd.png)
Here's the screenshot.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [O-FISH – design new Realm roles/rules to implement new data-sharing scheme](https://trello.com/c/f19ICTNa/407-o-fish-design-new-realm-roles-rules-to-implement-new-data-sharing-scheme)
