### ISSUE TITLE
Business listings aren't complete

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#166]
Business listings seem to be limited to the last 5 boarding records; it should be more like vessels, where all the records in the Realm are shown.

Searching for "Johnson" - I should see H.B. Johnson, but I don't:
![Screen Shot 2020-07-28 at 3 26 30 PM](https://user-images.githubusercontent.com/1767528/88711800-b838b100-d0e6-11ea-8b9a-b27cad555d67.png)

Searching for "Test" - I should see more than one record:
![Screen Shot 2020-07-28 at 2 03 17 PM](https://user-images.githubusercontent.com/1767528/88711832-c71f6380-d0e6-11ea-8c9e-56bb01aa5670.png)

Here's the data, looking from July 1st onwards (I limited it because I didn't want to see a ton of records).

MongoDB Enterprise atlas-l4abbo-shard-0:PRIMARY> db.BoardingReports.aggregate([{$match: {   agency:'Ecuadorian Galapagos', 'vessel.lastDelivery.business': {$ne: ''}, timestamp: {$gt : ISODate("2020-07-01 00:00:00.000Z")} }}, {$sort: {   timestamp: -1 }}, {$project: { 'vessel.lastDelivery.business': 1, timestamp: 1, _id: 0 }}]);
{ "timestamp" : ISODate("2020-07-28T17:17:43.407Z"), "vessel" : { "lastDelivery" : { "business" : "Jaws" } } }
{ "timestamp" : ISODate("2020-07-28T17:16:56.318Z"), "vessel" : { "lastDelivery" : { "business" : "Another business" } } }
{ "timestamp" : ISODate("2020-07-28T17:16:22.183Z"), "vessel" : { "lastDelivery" : { "business" : "Test business" } } }
{ "timestamp" : ISODate("2020-07-28T16:55:34.351Z"), "vessel" : { "lastDelivery" : { "business" : "P. Sherman Dentistry" } } }
{ "timestamp" : ISODate("2020-07-28T16:19:35.063Z"), "vessel" : { "lastDelivery" : { "business" : "Legal seafoods" } } }
{ "timestamp" : ISODate("2020-07-21T14:24:10.800Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-21T08:38:35.132Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-17T14:24:23.396Z"), "vessel" : { "lastDelivery" : { "business" : "!Test" } } }
{ "timestamp" : ISODate("2020-07-17T14:23:34.417Z"), "vessel" : { "lastDelivery" : { "business" : "!Test" } } }
{ "timestamp" : ISODate("2020-07-17T14:22:55.046Z"), "vessel" : { "lastDelivery" : { "business" : "! Test" } } }
{ "timestamp" : ISODate("2020-07-14T14:06:25.805Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-14T13:29:18.818Z"), "vessel" : { "lastDelivery" : { "business" : "P. Sherman" } } }
{ "timestamp" : ISODate("2020-07-14T12:45:30.279Z"), "vessel" : { "lastDelivery" : { "business" : "P. Sherman" } } }
{ "timestamp" : ISODate("2020-07-09T09:42:53.703Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-06T10:18:36.956Z"), "vessel" : { "lastDelivery" : { "business" : "P.Merlock Industry" } } }

**Comment by kojiba** [comment]
@Sheeri is this relevant for iOS?
cause I see and Android and Web screenshoots. 
I will also test this on iOS.

**Comment by kojiba** [comment]
Also cc @am-MongoDB here, 
Can be an issue regarding creds and clustering of data. 
Now for the Test Admin user I can see only 61 businesses total and 44 unique.

**Comment by Sheeri** [comment]
This is iOS, even though the screenshot is android (android had the same problem :D )

**Comment by Sheeri** [comment]
This is a Realm Sync issue.
