### ISSUE TITLE
 Fix AppStore symbols error

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#193]
Similar to issue 127 (which was fixed):

Dear Developer,

We identified one or more issues with a recent delivery for your app, "O-FISH" 0.22.4 (3). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90381: Too many symbol files - These symbols have no corresponding slice in any binary [450D3413-542D-3052-AAE8-165B23FAB14E.symbols, 58D8CC4B-31DB-3058-8AD5-3CF424709B3B.symbols]. 

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

**Comment by am-MongoDB** [comment]
The PR for #127 hadn't been merged – I'll do that now
