### ISSUE TITLE
Flag State preference not gotten from database

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#194]
The top of the flag state list is always "Ecuador" and "Panama" even when the data for the agency is otherwise (blank, or if there are other values like "United States").

If the agency data is blank or missing for the form data for Flag State, nothing should show up at the top (e.g. it starts at Afghanistan, Albania, Algeria, etc.) Otherwise the countries should be shown at the top in the order they are given (e.g. United States, Ecuador, Gabon should show up like that, before Afghanistan, Albania, Algeria).

**Comment by MykytaKiriushyn** [comment]
All the data comes from DB is displayed correctly. I think that ticket could be closed.
