### ISSUE TITLE
Fuzzy search?

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#198]
is it possible to have a fuzzy search in the app when searching for vessel names?

**Comment by am-MongoDB** [comment]
@Sheeri This is as close as we can get with Realm:

> For String properties, the LIKE operator may be used to compare the left hand property with the right hand expression: ? and * are allowed as wildcard characters, where ? matches 1 character and * matches 0 or more characters. Example: value LIKE '?bc*' matching strings like “abcde” and “cbc”.

Is that worth doing, or do we skip this requirement?

**Comment by Sheeri** [comment]
I say skip, it's going to be easier to teach users to just type in the first few letters, as opposed to wildcard languages.
