### ISSUE TITLE
Change 'on duty' and 'off duty' language

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#216]
We are not using the concept of 'on duty' and 'off duty' any more. The iOS design for the toggle is at https://mongodb.invisionapp.com/share/RWX43EEF567#/415937294_Home-Off_Duty The prompt to change status is at https://mongodb.invisionapp.com/share/RWX43EEF567#/415937301_Modal-Off_Duty_Alert The toggle showing 'at sea' is at https://mongodb.invisionapp.com/share/RWX43EEF567#/415937302_Home-On_Duty The 'duty report' should now be Patrol Summary as per https://mongodb.invisionapp.com/share/RWX43EEF567#/423507970_Home-On_Duty-Switch_Off

**Comment by am-MongoDB** [comment]
Already fixed
