### ISSUE TITLE
Need to know when there is no data vs. officer did not try to get data

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#218]
Sometimes there just is no data for a field - like when a crew member does not have a license number. Because of these cases the office would like to be able to check a 'none' checkbox so that the app knows there is no data for that. Data marked as 'none' should validate and not warn that it is empty. See basic design as per https://docs.google.com/document/d/1rDXmdlB3lfqAb7uAhR1u96LbyNaUyl3_2t2O_C0kI_E/edit#bookmark=id.ua1q0ri03hpz and the document at https://docs.google.com/document/d/1rDXmdlB3lfqAb7uAhR1u96LbyNaUyl3_2t2O_C0kI_E/edit# has all the screens and what fields should have checkboxes vs. not.

**Comment by Sheeri** [comment]
Given the complexity of this functionality along with drafts, we are going to stop work on this functionality and leave it out for now.

Thanks everyone for the work you've already done on this.
