### ISSUE TITLE
Done button on keyboard

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#220]
When a user is finished typing on the keyboard they got confused as to what to do next. There should be a 'Done' place that - when selected - the keyboard will disappear. 

The design for the ABC keyboard - https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937376_Boarding-Activity-Gear-Note_Type 

The design for the 123 keyboard https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937413_Boarding-Catch-Weight_Number_Entered 

And of course Done should be added to internationalization/localization - you do not have to localize it but it should be added to the Localizable.strings files.

**Comment by czuria1** [comment]
Hello! I'm interested in working on this issue 🙂

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you. (will check the PR now)
