### ISSUE TITLE
Patrol Summary record view

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#222]
When viewing the patrol summary - the back button on the top has the name of the vessel. This makes it appear that tapping back from the boarding record will take them back to the vessel profile. But tapping back takes them back to the patrol summary. Please change this to 'Back'.

**Comment by bladebunny** [comment]
This seems to have been done.  "Back" button now shows "Cancel".  I can change to "Back'" if that's still wanted.

**Comment by Sheeri** [comment]
Hi! Can you confirm which pages you see the words on? I think what I'm seeing is:

"Cancel" on the Patrol Summary page (which you get to by clicking the "At Sea" toggle after boarding at least one vessel and submitting a report.

If, on the Patrol Summary page, you click to one of the boardings, the title is "Boarding" and there is a button called "Back" on that page.

If that's what you see, then yes, this can be closed, and feel free to request work on another issue.

**Comment by Sheeri** [comment]
For clarification:

The patrol summary says “Cancel” which is correct:
![DC75CCCF-F200-43F4-8258-1F74CCA1C6BF](https://user-images.githubusercontent.com/1767528/95679852-78408080-0ba3-11eb-99c2-e3754fdb31ce.png)

And if I tap on the boarding i see this screen, which has “Back”, also correct:
![Uploading 40687A68-341E-4768-9C0A-68A43C130757.png…]()
