### ISSUE TITLE
Only open Realm when it is being used

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#233]
A realm is not meant to be read from a single location like this. It should be opened dynamically and as needed. If you want to pre-emptively open a realm to begin the "sync" or "connection" process, that can be passed around as needed

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Only open Realm when it is being used](https://trello.com/c/PUCJIdjW/212-only-open-realm-when-it-is-being-used)
