### ISSUE TITLE
Open Realm when user first logs in so that data is prefetched

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#234]
The Realm Objects will then be cached on the device so that subsequent queries are fast

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [iOS - Open Realm when user first logs in so that data is prefetched](https://trello.com/c/qZPYLtme/213-ios-open-realm-when-user-first-logs-in-so-that-data-is-prefetched)

**Comment by am-MongoDB** [comment]
Closing this issue as it doesn't improve performance:

> Hi Jason, I just wanted to check my observations on the effectiveness of pre-querying Realm. It’s appearing that all of the data is being synced to the app as soon as the user logs in (presumably for all documents that match the sync permissions set up in the Realm app for the Realm user). If I wait a while (after logging in) to open the first view that queries realm for the Objects then it finds and displays them immediately – if I don’t wait then the list is empty (here we’re not currently taking advantage of live queries as we straight away convert the resulting list of Objects to an array of View Models and so we won’t see any reports as they sync until the view is refreshed). If this is correct, then there’s no advantage in running a “pre-fetch” query, as that’s effectively done just by logging in?

> jason.flax:  yes, there is no real advantage on running a pre-fetch query, since we start syncing on login
