### ISSUE TITLE
Remove ViewModel for `DutyChange`

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#240]
When the app was built, Realm Objects weren't compatible with SwiftUI (could not conform to `Observable` with `@objc` annotated attributes in the `Object`. This has now changed - Realm `Object`s are now Observable out of the box. This should remove the need to have a View Model in most cases as the views can act on the model Objects directly

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get rid of View Model for `DutyChange`](https://trello.com/c/G6leuw4W/207-get-rid-of-view-model-for-dutychange)

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add extra analysis on how/whether to remove iOS view models](https://trello.com/c/wLY4dNOr/208-add-extra-analysis-on-how-whether-to-remove-ios-view-models)

**Comment by am-MongoDB** [comment]
See comments in this [related issue](https://github.com/WildAid/o-fish-ios/issues/241) to see why this has been moved to the `Blocked` state
