### ISSUE TITLE
Add a flag to the `Report` model to indicate that the report is currently being edited

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#242]

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update O-FISH model to include a flag to indicate that the report is a draft](https://trello.com/c/JNE9IAqW/293-update-o-fish-model-to-include-a-flag-to-indicate-that-the-report-is-a-draft)
