### ISSUE TITLE
EMS note does not work

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#247]
When selecting the paper clip in the 'Electronic Monitoring System' section on the 'Vessel' page - if I try to add a note nothing happens. A field should appear where I can write in a note and it should be saved to the appropriate place in Realm.

**Comment by Sheeri** [comment]
Verified it's still happening (v29)

**Comment by coltonlemmon** [comment]
I'd like to work on this, I've been able to replicate it. It seems like the note fields do get added but they don't appear until there is another change such as selecting photo or camera.

**Comment by Sheeri** [comment]
@coltonlemmon - awesome, thanks for offering to work on this! I have assigned it to you.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix iOS Notes issues](https://trello.com/c/xEwzWydP/440-fix-ios-notes-issues)
