### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#249]
When you click the avatar to get to the profile page - you should see this page - https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523459 

To be complete for this issue the following functionality must be in place: Close; Log Out; At Sea/Not At Sea toggle; Display name and email address; display red dot in the avatar if the status is 'Not At Sea' and a green dot if the status is At Sea; click 'Edit' to change the avatar.

**Comment by Sheeri** [comment]
After #248 is done.
