### ISSUE TITLE
When logging in, the busy screen disappears too quickly

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#256]
When logging in, an animated progress screen is displayed, but there is a delay between when that screen is removed and the patrol boat view opening

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/npsrp2yZ/217-raise-new-issues-resulting-from-using-testing-the-apps)
