### ISSUE TITLE
Pre-boarding search record uniqueness

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#270]
In pre-boarding search records should be unique by name AND permit number. Currently it is based only on name so two vessels with the same name and different permit number show up as one record but they should show up as 2 different ones.

**Comment by Sheeri** [comment]
Screenshot of mobile app:
![Screen Shot 2020-09-09 at 4 36 42 PM](https://user-images.githubusercontent.com/1767528/92650989-be5fa700-f2ba-11ea-9993-e7d8d60cf4fc.png)

Screenshot of web app for vessels named "orca":
![Screen Shot 2020-09-09 at 4 37 53 PM](https://user-images.githubusercontent.com/1767528/92651258-d1727700-f2ba-11ea-917c-95b525da9796.png)

**Comment by akaktus** [comment]
@Sheeri On iOS side we don't have this issue. BTW we sort vessel by name and permit number. 
![Simulator Screen Shot - iPhone 11 - 2020-09-10 at 10 33 00](https://user-images.githubusercontent.com/17438295/92695457-252f9f80-f351-11ea-8832-08c54f3f6912.png)
