### ISSUE TITLE
Text too small in pill

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#274]
In pre-boarding record the pill text is too small. (e.g. "red" "Amber" "green")

**Comment by akaktus** [comment]
@ Sheeri In design we have font with next parameters: 12 px, semibold.  In app we use dynamic type size (.caption1 (12 px), semibold). So I guess that's all should show correctly according design. Please, close bug or describe bug more detailed.

**Comment by Sheeri** [comment]
Closing; this was a problem with the simulator.
