### ISSUE TITLE
Loading screen isn't cleared if try logging in with a bad username/password

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#282]

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/crgxnjIM/305-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix iOS loading screen](https://trello.com/c/H75emvmK/312-fix-ios-loading-screen)
