### ISSUE TITLE
Keyboard should disappear when a user scrolls on a page, or on a dropdown menu

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-ios#286]
The keyboard covers up information, and a mobile standard is to have the keyboard slide down when users scroll on a page, whether it be results, a menu, simply a form screen, or anything else. This is specifically an issue when on a dropdown menu (Catch, Gear, EMS type, Fishery, etc.) - and with no way to dismiss the keyboard, users can't even get to "Other," or anything below the top of the keyboard.

This is a serious usability issue.

**Comment by czuria1** [comment]
Hello! Can I work on this issue? I have an open PR at the moment by the way

**Comment by Sheeri** [comment]
@czuria1 thanks for being transparent about the open PR - yes, you can work on this even with an open PR. I've assigned it to you.
