### ISSUE TITLE
Risk text overflows from the "pill," specifically with translations

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-ios#287]
Issue:
![Screen Shot 2020-09-16 at 11 03 03 PM](https://user-images.githubusercontent.com/49571712/93415168-e5951600-f870-11ea-8736-fe5cf1750d9a.png)

Either have text go to next line and make the pill bigger, or stretch the size of the pill to fit the text horizontally

**Comment by pankova** [comment]
Hello! 🙂 Could I help you with it as Hacktoberfest participating?

**Comment by Sheeri** [comment]
Hi @pankova - we are requesting that folks only work on one issue at a time. When you are finished with the other issue (submit a PR or ask to be unassigned), we can assign this to you if nobody else has asked to do it.

**Comment by er-aman-gupta** [comment]
@Sheeri, can i pick this up?

**Comment by Sheeri** [comment]
Hi @er-aman-gupta  - I have assigned this to you.
