### ISSUE TITLE
draft boardings on home page - no drafts

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#294]
If there are no draft boardings - the home page should look like this: https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430515871 and when they click on draft boardings they get a screen that looks like this: https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523463

**Comment by am-MongoDB** [comment]
The second view should be implemented under https://github.com/WildAid/o-fish-ios/issues/296
