### ISSUE TITLE
draft boardings on home page - drafts exist

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#295]
If there are draft boardings - the home page should look like this: https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523454_Home-On_Duty-1_Unsaved where the number in the red circle next to 'Draft Boardings' is the number of drafts.

**Comment by am-MongoDB** [comment]
Should get the number by counting the number of Reports where `draft` is set to `true` and `reportingOffice` matches the current user
