### ISSUE TITLE
editing draft boardings

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#296]
When a user clicks the 'Draft Boardings' link and there is at least one boarding - they should see a screen where all the draft boardings are listed. There is also a 'back' functionality at the top to go back to the home page. When a record is selected the UI should have the boarding record populated and edit as a normal boarding record - at the end they can save or submit as per usual. Design is at https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523455 - you can click through the boarding record to see what happens. A user may edit (and submit or delete) draft boardings when they are 'Not At Sea' (but they may not create a new boarding record when they are not at sea).

**Comment by am-MongoDB** [comment]
This includes the work to implement the new view containing the list of draft boardings for this user, and launching the report editing view (including state to indicate how the editing behaviour should be different than when creating a new report
