### ISSUE TITLE
Cancel Boarding if the boarding is a draft

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#297]
If the boarding is a draft and the user clicks cancel boarding - they should see a screen that has 'Keep Editing' 'Save and Finish Later' and 'Delete Boarding' (not 'cancel boarding') so it is clear that cancel means their draft goes away. Design is at https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523446_Cancel_Draft_Boarding If they select 'Delete Boarding' they should see a modal that says 'Boarding Deleted' and go back to the list of draft boardings (the screen you get when you click 'Draft Boardings' from the home page) without that boarding on the list - because it’s been deleted.

**Comment by am-MongoDB** [comment]
Should call a cascading delete function (to be added) on the view model under https://github.com/WildAid/o-fish-ios/issues/300
