### ISSUE TITLE
Submit a draft boarding

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#298]
When editing a draft boarding - if the Save button is clicked and then the 'Submit' button - a modal should pop up that says 'Boarding Submitted' and then take the user back to the 'Draft Boardings' screen. Design as per https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430526540_Draft_Boarding-Finished (click 'Save' then 'Submit' to see the action).

**Comment by am-MongoDB** [comment]
As part of submitting, the `draft` attribute should be set in the `ReportViewModel` instance and then `save()` executing on it
