### ISSUE TITLE
Not at sea and drafts

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#299]
When a user with drafts changes status to 'Not at Sea' the patrol summary should appear with the addition of a total number of drafts and a dot next to each boarding record that is a draft. The color should be the same orange as the validation exceptions. From that page the user can select a boarding record to see the summary (whether or not it is a draft) or continue as usual or cancel. If a user wants to edit a draft record they will be trained to cancel and go to the home screeen where the draft boardings are. https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523456_Home-On_Duty-5_Unsaved

**Comment by am-MongoDB** [comment]
Note that you can find the total number of drives by filtering on reports that have the `draft` attribute set and `reportingOfficer` set to the current user
