### ISSUE TITLE
Not being given the option to prefill Vessel information when boarding an existing vessel

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#305]
The existing report for this vessel has a photo attachment, vessel name, and permit number filled in. When creating a new report for the same vessel, I'm not given the option to prefill the vessel information from the previous report.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by am-MongoDB** [comment]
May be the same issue as https://github.com/WildAid/o-fish-ios/issues/307 and may be caused by an upgrade to Xcode 12

**Comment by Sheeri** [comment]
Issue #307 has been fixed, and #315 and I cannot reproduce this issue. Is this still occurring?
