### ISSUE TITLE
Date picker isn't usable as most of it is off the bottom of the screen

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#306]
![image](https://user-images.githubusercontent.com/14197449/93864173-65314380-fcbc-11ea-9a1b-cc7a4725733d.png)

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)
