### ISSUE TITLE
Data lost when moving between tabs when boarding an existing vessel

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#307]
I start a new report for an existing vessel and then I add information to fields such as the vessel name and the captain. If I navigate to another pane and then navigate back - the data is lost.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by am-MongoDB** [comment]
May be the same issue as https://github.com/WildAid/o-fish-ios/issues/305 and may be caused by an upgrade to Xcode 12
