### ISSUE TITLE
Remove simulator version warning for Xcode 12

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#311]
`The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove simulator version warning for Xcode 12](https://trello.com/c/4YfYVE71/354-remove-simulator-version-warning-for-xcode-12)
