### ISSUE TITLE
Violation link not found when deleting crew member

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#316]
When deleting a crew member from a report, `removeItemClicked` in `CrewView.swift` fails to find the violation that's referencing that crew member

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)
