### ISSUE TITLE
".0" automatically added when entering weight

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#319]
If I type `1` then the input actually becomes `1.0`, and if I wanted to type `1.5`, I first have to delete the `.0`

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)
