### ISSUE TITLE
iOS: Offline login on app

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#32]
It would be great if we could login offline - would have to figure out security implications - but options are: 0) don't actually login, just store credentials (or hashed credentials?) to submit when online.
1) actual login info is in Realm db - for everyone, for last logged in user, for last 3 logged in users on device.

**Comment by am-MongoDB** [comment]
The app is designed to keep the current user logged in as much as possible (even after force-closing and restarting the app) so that it shouldn't be necessary for a user to need to login while offline.
What's the use case for this?

**Comment by Sheeri** [comment]
You are correct. This was an idea put forth a while back, before the app was coded/designed to keep the current user logged in. Will close.
