### ISSUE TITLE
The fill for warning/citations goes beyond the rounded ends of the pill

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#320]
<img width="203" alt="Screenshot 2020-09-24 at 10 07 43" src="https://user-images.githubusercontent.com/14197449/94136964-99903580-fe5d-11ea-9b2c-798d4dd2310d.png">

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)
