### ISSUE TITLE
Draft Boardings and going back

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#331]
Steps to reproduce:
Login, click on "Board Vessel", click "Add New Vessel", then click "Save" and save a draft.

Click on 'Draft Boardings' - the screen that appears, does not have the top heading of "Draft Boardings" and the < back arrow. It looks like the screen is shifted up.

You can see what it should look like by clicking on a draft boarding, then clicking "cancel"  and either "Save and Finish Later" or "Delete Boarding". 

This is a big problem if someone clicks "Draft Boardings" and there are no draft boardings - there's no way to escape that page. you have to force close the app and then log back in.

Here's an example of making a draft boarding, then going to drafts and selecting it, then deleting that boarding, this is what I see:
![IMG_9181](https://user-images.githubusercontent.com/1767528/95371977-edad0800-08a8-11eb-979b-fac0ed17ed9b.PNG)

(you can see that if you don't have that heading, it's just a page with an image and nowhere to go.

**Comment by pankova** [comment]
Hello! Sorry, could I get this issue? I have set the environment for https://github.com/WildAid/o-fish-ios/issues/289, but I haven't reproduced it yet. As for this, I meet this bug constantly and have thoughts on how to fix it :)

**Comment by Sheeri** [comment]
Ok, I have unassigned 289 and assigned you this.
