### ISSUE TITLE
For Flag State on Vessel Information Store Country Code

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#332]
On the Vessel Information page - when the user chooses a menu option for Flag State - the country code should be stored in the database - not the full name of the country. e.g. 'us' not 'United States' or 'ec' not 'Ecuador'.

**Comment by nugmanoff** [comment]
Hey there! Can I help you on this one as part of Hacktoberfest 2020?

**Comment by am-MongoDB** [comment]
Hi @nugmanoff I've assigned you to the issue - welcome to the project!
