### ISSUE TITLE
Add Dark Mode button and change the 'Me' page accordingly

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#347]
Users frequently find themselves in situations where they are using the app in very bright sunlight, or at night. Please add a Dark Mode button, and change the 'Me' page accordingly. 

This is the screen when the user clicks their avatar on the home screen. 

The screen should look like this - https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591779_Me
Dark mode is off by default, and has the light background; when Dark mode is toggled on, the dark theme should be applied. 

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode  
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode   
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

This profile setting should be stored on the device, not in the database. 

Dark mode should work either when the switch is toggled on, or when the switch is off but the device itself is in dark mode.

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

**Comment by bladebunny** [comment]
I'd like to take this.

**Comment by Sheeri** [comment]
Hi @bladebunny - thanks for offering to work on this! I have assigned it to you.

Our product, engineering and design team have further discussed it and decided that the dark mode toggle should always override the OS state. When the toggle is off, the app is in light mode. When the toggle is on, the app is in dark mode. 

(so, if the OS is in dark mode, and the app has the dark mode toggle off, the app is in light mode).

**Comment by bladebunny** [comment]
Also, I'm assuming that this should also update other views?  I'll add the colors if they aren't there already.  This change will have a pretty broad impact across views.  Will probably have to do it in chunks so as not to have a massive PR.  We can set the dark mode state in userdefaults -- and I'll add a settings wrapper - and the probably expose an Observable(s) for various settings changes that views/viewmodels want to subscribe to. Ordinarily this is something you could do once in a base UIViewController but I'll have to look into the best way to do this is SwiftUI so as to minimize the surface area of views needing to know about this.  Trying to avoid the amount of boilerplate/bookkeeping views need to do to add a new view.  May be unavoidable though. Just some thoughts...

**Comment by bladebunny** [comment]
Will probably make sense for me to create a series of PRs (colors, userdefults wrapper, view upadates, etc..) for the incremental work. If we can do that without closing the main issue.

**Comment by Sheeri** [comment]
If you want to make a series of PRs for the incremental work, that's totally OK, and I can make sure that it won't close the issue (or if it does close, I'll reopen it 👍). 

Please note that I'm not expecting you to do ALL the colors and ALL the elements/views/etc. Just the ones for the "Me" page. In this way we can spread out the work of the dark mode project to multiple engineers, and it doesn't all fall on one person.

**Comment by bladebunny** [comment]
Just and FYI - for some reason I was not able to pick up the conflict in my last PR.  Re-added PR that is current and includes only Dark Mode work.  Suitable for closing once it passes review.
