### ISSUE TITLE
Ensure that no deployment-specific values hit GitHub

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#348]
**Describe the bug**
Ensure that no deployment-specific values (e.g. the Realm app-id can accidentally be pushed to GitHub

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Take iOS app-id out of GitHub](https://trello.com/c/htug01ZF/400-take-ios-app-id-out-of-github)
