### ISSUE TITLE
Should be testing with Xcode 12 and iOS14

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-ios#364]
**Is your feature request related to a problem? Please describe.**
We should assume that the majority of our users will be running the latest GA version of iOS – that currently means iOS14.0 and Xcode 12. We should test on that platform, rather than older ones/

**Describe the solution you'd like**
Update the settings in Xcode.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move all testing to iOS14](https://trello.com/c/sr7iWiRY/432-move-all-testing-to-ios14)
