### ISSUE TITLE
Delete EMS note crash

### ISSUE THREAD

**Issue by coltonlemmon** [WildAid/o-fish-ios#368]
**Describe the bug**
When deleting an EMS note in EMSInputView the app crashes with an index out of bounds error:
Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444

**To Reproduce**
1. Go to EMSInputView
2. Add note
3. Click on delete button.
4. App crashes

**Expected behavior**
The app should not crash and the note should simply be deleted.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.0.1

**Comment by coltonlemmon** [comment]
Also note that until the fix for issue #247 is merged to test this you have to take additional steps to add a note field:
1. Add note
2. Add photo
3. Go to photo library and hit cancel(This reloads the EMS view so the previously added note appears.)
4. Delete note
5. App crashes

**Comment by am-MongoDB** [comment]
This happens when deleting any note - not just for EMS

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix iOS Notes issues](https://trello.com/c/xEwzWydP/440-fix-ios-notes-issues)
