### ISSUE TITLE
iOS dark mode: home screen

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#376]
The latitude/longitude box on the home screen in dark mode does not show the proper colors.

There was a lot of setup in https://github.com/WildAid/o-fish-ios/pull/361/files and the fix for this issue should be in the same style and reuse code where possible.

**Is your feature request related to a problem? Please describe.**
In dark mode, this page should look like this:
https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591778_Home

The latitude/longitude box is definitely not correct. Also please check the other elements on the page, including the blue color of the "Board Vessel" button.

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

**Comment by jkreller** [comment]
Hey @Sheeri! May I do that one? :)

**Comment by Sheeri** [comment]
@jkreller please do!

**Comment by jkreller** [comment]
Added #389
