### ISSUE TITLE
Add skip-list to Localization management script

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#383]
In #369 a localization script was made. We would like a skip-list feature to be added, as well as a default skip list that contains three strings to skip:

%@
:
R%@ C%@

The strings should match the full string (e.g. ":" should match that string, not something like "hi: there").

Can we make that be a file in the scripts directory please? that way we can have a list that stays with the code.....(it can be on by default, and people should be able to specify a different file, or no skip list).

e.g.

--skip-list=/path/to/file - by default, "skip_list.txt" in the current directory
--skip-list=false - don't use a skip list.

**Comment by Sheeri** [comment]
@bladebunny let me know if you want to pick this issue up.

**Comment by bladebunny** [comment]
Sure, I can take it.

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.
