### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by evnik** [WildAid/o-fish-ios#385]
**Describe the bug**
The tests target `O-FISHTests` couldn't be built

**To Reproduce**
1. Get the latest version of the `main` branch (ea26f01)
2. Try to run tests
3. Observe the tests target couldn't be built

**Expected behavior**
Tests are buildable and passing

**Comment by Sheeri** [comment]
Hi @evnik z thanks for taking the initiative to make and fix this issue! I have assigned it to you. 

Since your PR is pending review - if you like you can pick up another issue to work on. We have lots of opportunities for unit and integration tests if that's your thing!
