### ISSUE TITLE
GPS location (blue dot) shows incorrectly/inaccurately on the map

### ISSUE THREAD

**Issue by shapljts** [WildAid/o-fish-ios#392]
**Describe the bug**
The device GPS location (depicted by blue dot) is not showing my position accurately on the map in the initial map view (Patrol Boat View?) that loads up after I log in. This inaccuracy is worse the further zoomed out the map is. I did note that the latitude/longitude coordinates do accurately reflect the GPS location, so this is likely an issue with how the location is being updated on the map view, itself.

Also, I noticed that the blue dot remains centered in the screen, not anchored to a location on the map when I pan the map. This behavior is not expected and is very different from that of other standard map-based apps, including Apple Maps (the SDK being at least partially used) and Google Maps.

**To Reproduce**
1. Open app, log in if needed
2. When first view loads, tap the GPS/show location button in upper right corner of map view (if presented with prompt to allow location use, tap While using app.
3. Note that blue dot does not reflect location on the map accurately
4. Zoom in and tap location button again.
5. Note that blue dot accuracy has improved, but is still not accurate
6. Pan the map
7. Note that blue dot does not remain anchored on the map, but remains centered on the screen as you pan

**Expected behavior**
Expected behavior on tapping the GPS (assuming I have already granted permission) would be that it would pan and zoom in to an extent best for your use case (neighborhood-ish level in Apple and Google Maps), representing the device location with a blue dot (or similar) placed at the coordinates of the device GPS. Then, when the user pans or zooms, the blue dot remains at the device GPS location on the map; the blue dot should only move if the device moves.

**Screenshots**
May provide these later, when I'm not working from my home office. To see expected behavior, open Apple Maps or Google Maps and tap on the GPS/location button.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS X]
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.4
 - Browser Safari, stock

**Additional context**

**Comment by Sheeri** [comment]
can't reproduce
