### ISSUE TITLE
prefill duplications

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#401]
When you board a vessel that has been boarded before, and prefill the crew, then save a draft....

Then you edit the draft and go to Crew, it asks if you want to prefill again. it should just save what you do.

**Comment by o-fish-wildaid** [comment]
Cannot replicate

**Comment by Sheeri** [comment]
Dmitry, can you replicate this bug? if not, feel free to close it.

**Comment by Dmitriy-Holovnia** [comment]
Cannot replicate
