### ISSUE TITLE
Orange validators should show up

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#406]

**Comment by Sheeri** [comment]
Right now, the name of the screen at the top is orange if you skip things - whether you skip using the button at the bottom to go to the next screen, without filling something in, or you navigate at the top and go directly to the page.

What doesn't show up in orange, is if you skip by picking a screen at the top (e.g. you go from Vessel Information right to Violations), the fields themselves on the orange pages don't show up (orange circle with ! inside). If I skip using the bottom button, and navigate back, I see the fields with the orange validators.

Hopefully that makes sense?

**Comment by Sheeri** [comment]
Here’s a video:

Uploading IMG_9427.MOV…
