### ISSUE TITLE
Saving a boarding record adds MPA field if appropriate

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-ios#452]
If the location of a boarding is inside the polygon of an MPA, the boarding record should add the field:

inspection.summary.MPA
and the value should be saved as a string that matches the MPA.name from the MenuData collection. e.g. "Galapagos" or "Cocos Island Marine Preserve" are the 2 possible values right now.

**Comment by Sheeri** [comment]
What are the implications with the Realm schema, and the android app? will putting this in, break the android app?

**Comment by Dmitriy-Holovnia** [comment]
The MPA field is optional so it didn't break the android app.
