### ISSUE TITLE
Vessel Profile

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#52]
As per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.l5vflqjb5z2u font size of vessel name should be 20pt; font size of permit should be 15pt; spacing should match design in https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937316

**Comment by akaktus** [comment]
Done
