### ISSUE TITLE
Login on iOS

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#72]
As per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.vki0kj3z6d0z - Log In button should be disabled until user enters an email AND password. This eliminates the need for the Error modal.

Also should be 16pt between username and password fields.

**Comment by akaktus** [comment]
It was implemented in scope another enhancement.
