### ISSUE TITLE
Pill colors and weight

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#75]

**Comment by Sheeri** [comment]
as per: https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.l6adi65ne4op

Pill colors should be as follows:
Red
Background: #F6D4D4
Text color: #891515

Green
Background: #DEEFE5
Text color: #006128

Amber
Background: #FFECBC
Text color: #614500 

Pill text should be semibold weight
