### ISSUE TITLE
Camera functionality

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#81]
As per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=kix.glirbgjnkyve - Dismiss should say "Back", slide down should also do the same as "Back". For multiple photos, can we have thumbs on the bottom, and a way for users to slide through them?

**Comment by Sheeri** [comment]
Fixed by using the camera UI itself - there's no "dismiss" or "back", just the regular "cancel" and "use this photo/retake" iOS users are accustomed to.
