### ISSUE TITLE
Number pickers

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#86]
Globally, for all number pickers, as per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.r7dlxqqfe5pj - there should be a “done” button above keyboard to dismiss the keyboard.

**Comment by MykytaKiriushyn** [comment]
Not actual behavior. Currently using format with degrees. minutes and seconds
