### ISSUE TITLE
Replace "Return" with "Next" on keyboard to move between fields

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#87]
As per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.a3z6w9dp6yu

"Return" implies a line break. 

Can we have the keyboard say “next” on the button right, and take users to the next field? 

If not, have it say “done” instead of “return,” because “return” may imply a line break.

This change should be "global" for all one-line text fields (but not for text areas like notes where a line break might be wanted).

Steps to reproduce:
Board vessel
click "add new vessel"
Tap "Vessel Name"
Keyboard shows up with "return" in the lower right. If you click it, it will act as 'Done'.

**Comment by Sheeri** [comment]
Confirmed this is still an issue.

**Comment by pankova** [comment]
Hello! Could I get this issue? :) I made PR with other

**Comment by Sheeri** [comment]
@pankova Sure, I've assigned it to you. Thanks for all your continued hard work on O-FISH, we really appreciate it!

**Comment by pankova** [comment]
> @pankova Sure, I've assigned it to you. Thanks for all your continued hard work on O-FISH, we really appreciate it!

Thank you! I'm really glad to be part of so a valuable project! ☺️
