### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#91]
As per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.2n6i28klmm3k - Date picker should only cover the bottom part of the page, and “Select” button should be blue, and styled according to the InVision at https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937337

**Comment by akaktus** [comment]
Done
