### ISSUE TITLE
Blank tab/field interactivity

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#93]
Globally for all blank tabs/fields, as per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.vf0z58y7p93f - Tabs should only be orange if they’ve been skipped. 

If a user selects “Continue” from the snackbar as a result of blank fields, then the tab doesn’t need to be orange. This is to highlight that skipping a tab is more severe of an action than leaving a blank field. 

Steps to reproduce: 
Board a vessel
Add New Vessel
Click "Crew" - "continue with empty fields?" shows up
Click "Continue to Crew"
And you can see Vessel is orange.

**Comment by Sheeri** [comment]
Verified this is still an issue.
