### ISSUE TITLE
Weight Unit Picker

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#99]
As per https://docs.google.com/document/d/1K-iSxSOaCVdMJweiwOUwVO92tVaCU7FjvlUmco11tgY/edit#bookmark=id.eklucwvffvsd - The weight unit picker should not take up the entire screen - original design is https://mongodb.invisionapp.com/share/RWX43EEF567#/415937414_Boarding-Catch-Weight_Unit_Picker

**Comment by kojiba** [comment]
Already done in scope of #4
